version: '3'

services:
  nginx-rtmp:
    image: tiangolo/nginx-rtmp
    ports:
      - "1935:1935"  # RTMP
      - "8080:8080"  # HTTP for HLS playback
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./hls:/hls  # Fixed path to store HLS files
    restart: unless-stopped
    container_name: nginx-rtmp-server
    # Add host network mode for better connectivity
    network_mode: "host"